on: # To web-hook to which events: "push", "PR" (creation or modificaiotn), "manual trigger"
  push: # e-enable to avoid many clicks each time. Comment out later.
  pull_request:
  workflow_dispatch:

# Workflow for experiment 19: ASIC using OpenLANE and/or FPGA

jobs:
  verilog-yosis-environment-prepare:
    # verilog-yosis-full:

    runs-on: ubuntu-latest # docker image
    # each is a fresh, isolated VM or container
    # can target a different OS, VM type, or custom label
    # it’s a GitHub-hosted runner label. Not a "docker run -it ubuntu"
    # List: https://github.com/actions/runner-images
    #   preloaded with tools
    #  not docker image!
    #
    # Across jobs: (if differnt, or even the same "runner-image")
    #    not shared live
    #    No layer reuse across jobs
    #    No container layering

    # `job`s are fully isolated: state, image-contents.
    # Different filesystem. All layers are separate.
    # environment : different, not shared, instantiated.
    # No disk layer sharing
    # Different processes
    # No memory sharing


    # Hence, a new concept: "runner-image", which is Not "docker-image". But parallels that.

    # So, How to share data between jobs:
    #    artifacts: upload-artifact / download-artifact
    #    "cache keys"

    # So, how to use docker-image as a "runner-image"? (instead of.)
    #    Add a `container.image: yosys/yosys:latest`
    #      private (docker) registries possible
    #      Not to confise with "runner-image registries", e.g. https://github.com/actions/runner-images
    #  A host VM, and the docker image is inside it:
    #     inside the specified Docker container, which is "inside" (nested docker in docker).
    #     you can specify its docker-registry too (since it is fetched inside that "VM": meta-image)
    #     Hence, runner-image is a meta-image (VM-docker relationship, that is nested).


    # Conceptology:
    #   * runner-image
    #   * cache-key
    #   * artifact


    steps:

      - name: Prepare environment pyenv + ubuntu (to be moved to a docker image)
        run: |
          set -eux
          # see also : https://gist.github.com/jprjr/7667947

          export PYTHON_VERSION=3.12.3
          # Yosys says it is tested on 3.6.

          echo "
            export PYTHON_VERSION=$PYTHON_VERSION
          " >> "$GITHUB_ENV"

          sudo apt-get update

          sudo apt-get install -y --no-install-recommends \
            make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
            libsqlite3-dev wget ca-certificates curl llvm libncurses5-dev \
            libncursesw5-dev \
            xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev mecab-ipadic-utf8 \
            git \
            make

          echo "Ready to install pyenv"

          # pyenv is not in apt
          # sudo apt-get install -y  pyenv

          export PYENV_ROOT="$HOME/dot.pyenv"
          # mkdir -p "$PYENV_ROOT"
          curl https://pyenv.run | bash

          export PYENV_ROOT="$HOME/dot.pyenv"
          mkdir -p "$PYENV_ROOT"

          # DRY:
          export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

          pyenv init  # dont miss this

          eval "$(ssh-agent -s)"
          echo "pyenv ssh-agent eval succeeded."
          echo "Pre-update pyenv version:"
          pyenv version
          python --version

          pyenv update \
              || echo "err code: $?"
              || :  # A non-critical step that may fail. FIXME.
          # Can be slow:
          pyenv install $PYTHON_VERSION
          pyenv global $PYTHON_VERSION
          # pyenv shell $PYTHON_VERSION
          pyenv rehash

          echo "Done installing pyenv"

          # Set up environment for the next steps

          echo "export PYENV_ROOT=\"$PYENV_ROOT\"" >> "$GITHUB_ENV"
          echo '
            export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
          ' >> "$GITHUB_ENV"
          # The "$GITHUB_ENV" is automatically sourced in the next steps
          # eval "$(ssh-agent -s)" # You cannot GITHUB_ENV this. Repeat at each step.
          # pyenv version
          # python --version

      - name: Test use of pyenv
        run: |
          set -eux
          echo 'debug1'
          echo "GITHUB_ENV=$GITHUB_ENV"
          env
          echo
          echo $PYENV_ROOT
          eval "$(ssh-agent -s)"
          echo 'debug2'
          env || :
          echo 'debug3'
          pyenv version || : # Why fails?

          python --version

          # more information about the environment
          pyenv global
          pyenv versions
          pyenv version-file
          pyenv which python3
          pyenv exec echo "$(python3 --version)"



          # All future steps need to start with:
          # set -eux ; eval "$(ssh-agent -s)"

jobs:
  verilog-yosis-full:
    # amaranth-verilog-yosis-asic
    # riscv-formal:  # job name
    needs: verilog-yosis-environment-prepare

    runs-on: ubuntu-latest # docker image?

    # initiate experiment 19: ASIC using OpenLANE

    steps:

      - name: cp my neurasic1.v
        run: |
          echo '
            export TARGET_DIR="experiments/19_asic_lane/yosis-build"
          ' >> "$GITHUB_ENV"
          TARGET_DIR="experiments/19_asic_lane/yosis-build"
          mkdir -p "$TARGET_DIR"
          pwd
          cd "$TARGET_DIR"
          pwd

      - name: Checkout my verilog file
        uses: actions/checkout@v4 # registered (official) GH Action name
        with:
          sparse-checkout: | # pull a single file
            experiments/19_asic_lane/neurasic1.v
          sparse-checkout-cone-mode: false

      - name: skipped
      #- name: Checkout riscv-formal
        # never run:
        # if: never()
        if: false # never run
        uses: actions/checkout@v4
        with:
          #repository: YosysHQ/riscv-formal
          #path: experiments/19_asic_lane/build/riscv-formal
          # repository: YosysHQ/????
          # https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2024-06-04
          # https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2025-07-21
          # https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2025-07-21/oss-cad-suite-linux-x64-20250721.tgz
          # ./builder.py build --target=yosys : to create docker image
          # `click` ? https://pypi.org/project/click/
          path: experiments/19_asic_lane/yosis-build

      - uses: YosysHQ/setup-oss-cad-suite@v3
        # https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2025-07-01
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract OSS CAD Suite
        run: |
          set -eux ; eval "$(ssh-agent -s)"

          cd "$TARGET_DIR"
          wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2025-07-21/oss-cad-suite-linux-x64-20250721.tgz
          tar -xvzf oss-cad-suite-linux-x64-20250721.tgz
          ls -alth

      - name: cp my neurasic1.v
        run: |
          set -eux ; eval "$(ssh-agent -s)"

          # TARGET_DIR="experiments/19_asic_lane/yosis-build"
          # mkdir -p "$TARGET_DIR"
          echo "TARGET_DIR: $TARGET_DIR"
          cp experiments/19_asic_lane/neurasic1.v --target-directory="$TARGET_DIR"
          cd "$TARGET_DIR"

      - name: make checks
        run: |
          set -eux ; eval "$(ssh-agent -s)"

          # export TARGET_DIR="experiments/19_asic_lane/yosis-build"
          cd "$TARGET_DIR"
          echo "empty1"
          pwd
          echo "This will fail. Under construction (1)"
          make checks -j$(nproc)
          # see https://github.com/YosysHQ/picorv32/blob/main/Makefile

      - name: make check
        run: |
          set -eux ; eval "$(ssh-agent -s)"

          # cd riscv-formal/cores/picorv32
          # make check
          export TARGET_DIR="experiments/19_asic_lane/yosis-build"
          cd "$TARGET_DIR"
          echo "empty2"
          pwd
          echo "Under construction (2)"

  quick-build:
    needs: verilog-yosis-environment-prepare
    runs-on: ubuntu-latest # same
    steps:

      - name: TBC
        run: |
          set -eux ; eval "$(ssh-agent -s)"

          echo "Check environment variables"
          env
          pwd
          cd "$TARGET_DIR"
          pwd
          ls
          pyenv version
          python --version


# Inspirations from:
# https://github.com/YosysHQ/picorv32/blob/main/.github/workflows/ci.yml
# 87c89acc18994c8cf9a2311e871818e87d304568

# /myvol/tpu_poc/qtpu/dev-env
